addSbtPlugin("pl.project13.scala" % "sbt-jmh"       % "0.3.4")
addSbtPlugin("org.scoverage"      % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"  % "2.0.0")
addSbtPlugin("com.eed3si9n"       % "sbt-unidoc"    % "0.4.2")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"       % "1.1.2")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"       % "1.0.0")
addSbtPlugin("no.arktekk.sbt"     % "aether-deploy" % "0.21")
addSbtPlugin("com.github.gseitz"  % "sbt-release"   % "1.0.9")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"      % "1.2.10" )
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"  % "0.14.9")
