addSbtPlugin("com.eed3si9n"       % "sbt-assembly"  % "0.14.10")
addSbtPlugin("com.eed3si9n"       % "sbt-unidoc"    % "0.4.2")
addSbtPlugin("com.github.gseitz"  % "sbt-release"   % "1.0.13")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"       % "2.0.1")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"       % "1.0.0")
addSbtPlugin("no.arktekk.sbt"     % "aether-deploy" % "0.23.0")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"      % "2.1.0" )
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"  % "2.2.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage" % "1.6.1")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"  % "3.8.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"       % "0.3.7")
